import { Button, VerticalBox, ListView } from "std-widgets.slint";

export component MainApp inherits Window {
    width: 450px;
    height: 300px;

    Button{
        x: 20px;
        y: 20px;
        primary: true;
        height: 35px;
        width: 25%;
        text: "Add ToDo";
    }

    VerticalBox {
        padding-top: 70px;
        width: 100%;
        height: 100%; // Adjust height as needed

            ListView {
                    width: 100%;
                    height: 100%;
                    for data in [
                        { text: "Blue", color: #0000ff, bg: #eeeeee},
                        { text: "Red", color: #ff0000, bg: #eeeeee},
                        { text: "Green", color: #00ff00, bg: #eeeeee},
                        { text: "Yellow", color: #ffff00, bg: #222222 },
                        { text: "Black", color: #000000, bg: #eeeeee },
                        { text: "White", color: #ffffff, bg: #222222 },
                        { text: "Magenta", color: #ff00ff, bg: #eeeeee },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },
                        { text: "Cyan", color: #00ffff, bg: #222222 },

                    ] : Rectangle {
                        height: 30px;
                        background: data.bg;
                        width: parent.width;
                        Text {
                            x: 0;
                            text: data.text;
                            color: data.color;
                        }
                    }
                }
        }
}