import { Button, VerticalBox, ListView } from "std-widgets.slint";

export component MainApp inherits Window {
in property <[string]> todos;
    width: 450px;
    height: 300px;

    Button{
        x: 20px;
        y: 20px;
        primary: true;
        height: 35px;
        width: 25%;
        text: "Add ToDo";
    }

    VerticalBox {
        padding-top: 70px;
        width: 100%;
        height: 100%; // Adjust height as needed

            ListView {

                    width: 100%;
                    height: 100%;
                    for data in todos : Rectangle {
                        height: 30px;
                        background: darkblue;
                        width: parent.width;
                        Text {
                            x: 0;
                            text: data;
                            color: white;
                        }
                    }
                }
        }
}